name: skript-oraxen
authors: [Asleepp]
description: A Skript Addon that adds useful syntax to be used in conjunction with Oraxen
api-version: 1.13
version: 1.0
main: me.asleepp.skriptoraxen.SkriptOraxen
depend: [Skript, Oraxen]